// Generated by CoffeeScript 1.7.1
(function() {
  var coffee, gulp, gutil, jade, sass;

  gulp = require("gulp");

  gutil = require("gulp-util");

  coffee = require("gulp-coffee");

  jade = require("gulp-jade");

  sass = require("gulp-sass");

  gulp.task("coffee", function() {
    return gulp.src("src/coffee/**/*.coffee").pipe(coffee({
      bare: true
    }).on("error", gutil.log)).pipe(gulp.dest("out/js/"));
  });

  gulp.task("jade", function() {
    return gulp.src("src/jade/**/*.jade").pipe(jade()).pipe(gulp.dest("out/views/"));
  });

  gulp.task("sass", function() {
    return gulp.src("src/sass/**/*.scss").pipe(sass()).pipe(gulp.dest("out/css/"));
  });

  gulp.task("vendor", function() {
    return gulp.src("src/vendor/**/*.*").pipe(gulp.dest("out/vendor/"));
  });

  gulp.task("dev", ["coffee", "jade", "sass", "vendor"]);

}).call(this);
